import { useState, useMemo, useRef } from "react";
import {
  FiSearch,
  FiFilter,
  FiExternalLink,
  FiPause,
  FiPlay,
  FiMoreVertical,
  FiEdit2,
  FiTrash2,
  FiChevronDown,
  FiChevronLeft,
  FiHeart,
  FiClock,
} from "react-icons/fi";
import { ClipCard } from "../../components/ui/Card/ClipCard";
import type { Clips } from "../../hooks/jobs/clips";
import toast from "react-hot-toast";
import { deleteJob } from "../../lib/utils/JobsDeleter";
import type { Job } from "../../hooks/jobs/jobs";
import type { Profile } from "../../types/profile";
import { updateJob } from "../../lib/utils/JobsUpdater";


interface ClipsLibraryProps {
  clips: Clips[];
  jobs: Job[];
  profile: Profile;
  refetchJobs: () => void;
}

export const ClipsLibrary = ({ clips, jobs, profile, refetchJobs }: ClipsLibraryProps) => {
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<"latest" | "oldest">("latest");
  const [statusFilter, setStatusFilter] = useState<"all" | Job["status"]>(
    "all"
  );
  const [selectedJob, setSelectedJob] = useState<Job | null>(null);
  const [showStatusMenu, setShowStatusMenu] = useState(false);

  // 🔹 new filters
  const [clipView, setClipView] = useState<
    "all" | "favorites" | "longest" | "shortest"
  >("all");

  const filteredJobs = useMemo(() => {
    return jobs
      .filter((job) => {
        const term = search.toLowerCase();
        const matchesSearch =
          job.title.toLowerCase().includes(term) ||
          job.status.toLowerCase().includes(term);
        const matchesStatus =
          statusFilter === "all" ? true : job.status === statusFilter;
        return matchesSearch && matchesStatus;
      })
      .sort((a, b) =>
        filter === "latest"
          ? new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
          : new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
      );
  }, [jobs, search, filter, statusFilter]);

  const filteredClips = useMemo(() => {
    if (!selectedJob) return [];

    let jobClips = clips
      .filter((clip) => clip.jobId === selectedJob.id)
      .sort((a, b) =>
        filter === "latest"
          ? new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
          : new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
      );

    // Apply clipView filter
    if (clipView === "favorites") {
      jobClips = jobClips.filter((clip) => clip.favourite);
    } else if (clipView === "longest") {
      jobClips = [...jobClips].sort((a, b) => b.duration - a.duration);
    } else if (clipView === "shortest") {
      jobClips = [...jobClips].sort((a, b) => a.duration - b.duration);
    }

    return jobClips;
  }, [clips, selectedJob, filter, clipView]);

  return (
    <div className="min-h-screen px-1 sm:px-6 py-2 bg-gray-50">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-8">
          {/* Left side (Back + Title) */}
          <div className="flex items-center gap-3">
            {selectedJob && (
              <button
                onClick={() => setSelectedJob(null)}
                className="flex items-center gap-2 text-purple-600 hover:text-purple-800 font-medium transition"
              >
                <FiChevronLeft className="text-2xl cursor-pointer" />
              </button>
            )}
            <div>
              <h1 className="text-2xl font-semibold text-gray-900 tracking-tight">
                {selectedJob ? `${selectedJob.title} Clips` : "Content Library"}
              </h1>
              <p className="text-gray-500 mt-1 text-sm">
                {selectedJob
                  ? "All clips generated by this job."
                  : "Manage and monitor your AI clip generation projects."}
              </p>
            </div>
          </div>

          {/* Right side (Search + Filters) */}
          <div className="flex flex-wrap items-center gap-3 mt-5 sm:mt-0 justify-end">
            {!selectedJob && (
              <>
                {/* 🔍 Search */}
                <div className="relative">
                  <FiSearch className="absolute left-3 top-2.5 text-gray-400 text-sm" />
                  <input
                    type="text"
                    placeholder="Search jobs..."
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    className="pl-9 pr-4 py-2 w-56 bg-white border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-purple-500 outline-none transition"
                  />
                </div>

                {/* 🔄 Sort Button */}
                <button
                  onClick={() =>
                    setFilter(filter === "latest" ? "oldest" : "latest")
                  }
                  className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg text-sm font-medium hover:bg-gray-50 transition"
                >
                  <FiFilter className="text-gray-500" />
                  {filter === "latest" ? "Latest" : "Oldest"}
                </button>

                {/* 🧩 Status Filter */}
                <div className="relative">
                  <button
                    onClick={() => setShowStatusMenu((prev) => !prev)}
                    className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg text-sm font-medium hover:bg-gray-50 transition"
                  >
                    <span className="capitalize">
                      {statusFilter === "all" ? "All Statuses" : statusFilter}
                    </span>
                    <FiChevronDown className="text-gray-500" />
                  </button>

                  {showStatusMenu && (
                    <div
                      className="absolute right-0 mt-2 w-40 bg-white border border-gray-100 rounded-lg shadow-lg z-20"
                      onMouseLeave={() => setShowStatusMenu(false)}
                    >
                      {[
                        "all",
                        "ready",
                        "queued",
                        "processing",
                        "completed",
                        "failed",
                      ].map((status) => (
                        <button
                          key={status}
                          onClick={() => {
                            setStatusFilter(status as any);
                            setShowStatusMenu(false);
                          }}
                          className={`w-full text-left px-4 py-2 text-sm capitalize hover:bg-gray-50 ${
                            statusFilter === status
                              ? "text-purple-600 font-medium"
                              : "text-gray-700"
                          }`}
                        >
                          {status}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              </>
            )}

            {/* 🎛️ Clip filters (only visible when viewing clips) */}
            {selectedJob && (
              <div className="flex items-center gap-2">
                {[
                  { id: "all", label: "All" },
                  { id: "favorites", label: "Favorites", icon: <FiHeart /> },
                  { id: "longest", label: "Longest", icon: <FiClock /> },
                  { id: "shortest", label: "Shortest", icon: <FiClock /> },
                ].map(({ id, label, icon }) => (
                  <button
                    key={id}
                    onClick={() => setClipView(id as any)}
                    className={`flex items-center gap-1 px-3 py-1.5 text-sm rounded-lg border transition-all ${
                      clipView === id
                        ? "bg-purple-100 text-purple-700 border-purple-200"
                        : "bg-white text-gray-600 border-gray-200 hover:bg-gray-50"
                    }`}
                  >
                    {icon && <span className="text-xs">{icon}</span>}
                    {label}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Main Content */}
        {!selectedJob ? (
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {filteredJobs.length === 0 ? (
              <div className="text-center py-10 text-gray-500 text-sm col-span-full">
                No jobs found. Try creating one!
              </div>
            ) : (
              filteredJobs.map((job) => (
                <JobCard
                  key={job.id}
                  job={job}
                  onViewClips={() => setSelectedJob(job)}
                  onDeleteJob={async ()=>{
                    const loader = toast.loading(`Deleting job: ${job.title}`);
                    const response = await deleteJob(job.id);
                    toast.dismiss(loader);
                    
                    if(response === "error"){
                      toast.error("There was an error deleting this job");
                    }else{
                      refetchJobs();
                      toast.success("Job deleted successfully");
                    }
                  }}
                  refetchJobs={refetchJobs}
                />
              ))
            )}
          </div>
        ) : (
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {filteredClips.map((clip) => (
              <ClipCard key={clip.clipId} clip={clip} jobs={jobs} profile={profile} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

interface JobCardProps {
  job: Job;
  onViewClips: () => void;
  onDeleteJob: (id: string) => void;
  refetchJobs: ()=>void;
}
export const JobCard = ({
  job,
  onViewClips,
  onDeleteJob,
  refetchJobs
}: JobCardProps) => {
  const [isHovered, setIsHovered] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const [showMenu, setShowMenu] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [showRename, setShowRename] = useState(false); // 🟣 New rename modal toggle
  const [newTitle, setNewTitle] = useState(job.title);
  const videoRef = useRef<HTMLVideoElement>(null);

  const statusColors: Record<Job["status"], string> = {
    ready: "bg-gray-100 text-gray-700",
    queued: "bg-yellow-100 text-yellow-700",
    processing: "bg-blue-100 text-blue-700",
    completed: "bg-green-100 text-green-700",
    failed: "bg-red-100 text-red-700",
  };

  const togglePlay = () => {
    const video = videoRef.current;
    if (!video) return;
    if (isPlaying) {
      video.pause();
      setIsPlaying(false);
    } else {
      video.play().catch(() => {});
      setIsPlaying(true);
    }
  };

  const handleMenuAction = (action: "rename" | "delete") => {
    setShowMenu(false);
    if (action === "rename") setShowRename(true);
    if (action === "delete") setShowConfirm(true);
  };

  const confirmDelete = () => {
    setShowConfirm(false);
    onDeleteJob(job.id);
  };

  // 🟣 Stub for rename confirmation
  const confirmRename = async () => {
    setShowRename(false);
    const loader = toast.loading("Renaming job...");
    const response = await updateJob(job.id, {title: newTitle});
          toast.dismiss(loader);
    if(response === "success"){
      refetchJobs();
      toast.success("Job renamed!");
    }else{
      toast.error("There was an error renaming the job.")
    }
  };

  return (
    <div
      className={`relative flex flex-col bg-white/90 backdrop-blur-md border border-gray-200 rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-500 group`}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      style={{ minHeight: "460px" }}
    >
      {/* 🎥 Video Section */}
      <div className="relative aspect-video overflow-hidden bg-gray-100">
        <video
          ref={videoRef}
          src={job.videoUrl}
          loop
          playsInline
          preload="metadata"
          className={`w-full h-full object-cover transition-transform duration-700 ${
            isHovered ? "scale-105 brightness-105" : "scale-100 brightness-100"
          }`}
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent z-10 pointer-events-none" />

        {/* 🟢 Status Badge */}
        <span
          className={`absolute top-3 left-3 px-3 py-1 text-xs font-medium rounded-full shadow-sm z-20 ${
            statusColors[job.status]
          }`}
        >
          {job.status}
        </span>

        {/* ⋮ Menu */}
        <div className="absolute top-2 right-2 z-30">
          <button
            onClick={(e) => {
              e.stopPropagation();
              setShowMenu((prev) => !prev);
            }}
            className="p-2 rounded-full bg-white/80 hover:bg-white shadow-sm transition"
          >
            <FiMoreVertical className="text-gray-700 text-sm" />
          </button>

          {showMenu && (
            <div
              className="absolute right-0 mt-2 w-36 bg-white rounded-lg shadow-lg border border-gray-100 z-40"
              onMouseLeave={() => setShowMenu(false)}
            >
              <button
                onClick={() => handleMenuAction("rename")}
                className="w-full flex items-center gap-2 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50"
              >
                <FiEdit2 className="text-gray-500" /> Rename
              </button>
              <button
                onClick={() => handleMenuAction("delete")}
                className="w-full flex items-center gap-2 px-4 py-2 text-sm text-red-600 hover:bg-red-50"
              >
                <FiTrash2 className="text-red-500" /> Delete
              </button>
            </div>
          )}
        </div>

        {/* ▶️ Play/Pause Overlay */}
        {isHovered && (
          <button
            onClick={togglePlay}
            className={`absolute inset-0 z-20 flex items-center justify-center bg-black/30 backdrop-blur-[1px] transition-opacity duration-300 cursor-pointer ${
              isPlaying ? "opacity-0" : "opacity-100"
            }`}
          >
            <div className="p-4 rounded-full bg-white/90 shadow-md hover:scale-110 transition-transform duration-300">
              {isPlaying ? (
                <FiPause className="text-gray-800 text-xl" />
              ) : (
                <FiPlay className="text-gray-800 text-xl ml-0.5" />
              )}
            </div>
          </button>
        )}
      </div>

      {/* 📄 Content */}
      <div className="flex flex-col flex-1 p-5">
        <div className="flex-1">
          <h2 className="text-lg font-semibold text-gray-900 leading-snug mb-1 truncate">
            {job.title}
          </h2>
          <p className="text-sm text-gray-500 line-clamp-2 mb-4">
            {job.aiInstructions}
          </p>

          <div className="w-full h-2 rounded-full bg-gray-100 overflow-hidden mb-5">
            <div
              className={`h-full bg-gradient-to-r ${
                job.progress === 100
                  ? "from-emerald-400 to-green-500"
                  : "from-indigo-500 via-purple-500 to-pink-500"
              } transition-all duration-700`}
              style={{ width: `${job.progress}%` }}
            />
          </div>

          <div className="grid grid-cols-2 gap-y-1 text-xs text-gray-600">
            <p>
              <strong>Clips:</strong> {job.clipsGenerated}/
              {Number(job.clipsPerVideo) * Number(job.variationsPerClip)}
            </p>
            <p>
              <strong>Length:</strong> {job.clipLengthMin}s–{job.clipLengthMax}s
            </p>
            <p>
              <strong>Variations:</strong> {job.variationsPerClip}
            </p>
            <p>
              <strong>Videos:</strong> {job.videoCount}
            </p>
            <p className="col-span-2 text-gray-400 mt-1">
              Created: {new Date(job.createdAt).toLocaleDateString()}
            </p>
          </div>
        </div>

        <div className="flex justify-between items-center pt-5 mt-auto border-t border-gray-100">
          {job.youtubeUrl ? (
            <a
              href={job.youtubeUrl}
              target="_blank"
              className="flex items-center gap-1 text-sm text-indigo-600 hover:text-indigo-800 font-medium"
            >
              View YouTube <FiExternalLink className="text-xs" />
            </a>
          ) : (
            <span />
          )}

          {job.status === "completed" && (
            <button
              onClick={onViewClips}
              className="px-4 py-2 rounded-lg bg-gradient-to-r from-indigo-500 to-purple-600 text-white text-sm font-medium hover:from-indigo-600 hover:to-purple-700 transition-all shadow-md hover:shadow-lg cursor-pointer"
            >
              View Clips
            </button>
          )}
        </div>
      </div>

      {/* 💫 Glow */}
      <div
        className={`absolute inset-0 rounded-2xl transition-all duration-700 pointer-events-none ${
          isHovered ? "ring-4 ring-purple-200/60" : "ring-0"
        }`}
      />

      {/* ⚠️ Delete Confirmation */}
      {showConfirm && (
        <div className="fixed inset-0 z-[999] flex items-center justify-center bg-black/50 backdrop-blur-sm">
          <div className="bg-white rounded-xl shadow-lg p-6 w-[90%] max-w-sm text-center">
            <h3 className="text-lg font-semibold text-gray-900 mb-2">
              Delete this job?
            </h3>
            <p className="text-sm text-gray-500 mb-6">
              This action cannot be undone. Deleting this job will also
              permanently remove all{" "}
              <span className="font-medium text-gray-700">
                clips generated by this job
              </span>
              . Are you sure you want to delete
              <span className="font-medium text-gray-700"> "{job.title}"</span>?
            </p>

            <div className="flex justify-center gap-3">
              <button
                onClick={() => setShowConfirm(false)}
                className="px-4 py-2 rounded-lg bg-gray-100 hover:bg-gray-200 text-gray-700 text-sm font-medium transition"
              >
                Cancel
              </button>
              <button
                onClick={confirmDelete}
                className="px-4 py-2 rounded-lg bg-red-600 hover:bg-red-700 text-white text-sm font-medium transition"
              >
                Delete
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 🟣 Rename Modal */}
      {showRename && (
        <div className="fixed inset-0 z-[999] flex items-center justify-center bg-black/50 backdrop-blur-sm">
          <div className="bg-white rounded-xl shadow-lg p-6 w-[90%] max-w-sm text-center">
            <h3 className="text-lg font-semibold text-gray-900 mb-3">
              Rename Job
            </h3>
            <p className="text-sm text-gray-500 mb-4">
              Enter a new name for{" "}
              <span className="font-medium text-gray-700">"{job.title}"</span>.
            </p>

            <input
              type="text"
              value={newTitle}
              onChange={(e) => setNewTitle(e.target.value)}
              placeholder="New job name..."
              className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-purple-500 outline-none mb-6"
            />

            <div className="flex justify-center gap-3">
              <button
                onClick={() => setShowRename(false)}
                className="px-4 py-2 rounded-lg bg-gray-100 hover:bg-gray-200 text-gray-700 text-sm font-medium transition"
              >
                Cancel
              </button>
              <button
                onClick={confirmRename}
                disabled={!newTitle.trim()}
                className="px-4 py-2 rounded-lg bg-purple-600 hover:bg-purple-700 text-white text-sm font-medium transition disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Rename
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};





